name: CI/CD Application Deployment

on:
  push:
    branches: ["main"]

jobs:

  # -------------------
  # CI JOB
  # -------------------
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if npm run | grep -q test; then
            npm test
          else
            echo "No tests found, skipping..."
          fi

      - name: Build app
        run: npm run build


  # -------------------
  # CD JOB
  # -------------------
  cd:
    name: Docker Build, Push & Deploy to EC2
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------
      # Docker Login
      # -------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------------------
      # Build & Push Image
      # -------------------
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/buygun:0.3
          build-args: |
            VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}

      # -------------------
      # Setup SSH Key
      # -------------------
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      # -------------------
      # Deploy to EC2
      # -------------------
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF

          sudo docker stop buygun || true
          sudo docker rm buygun || true

          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/buygun:0.3

          sudo docker run -d \
            --name buygun \
            -p 80:4174 \
            ${{ secrets.DOCKERHUB_USERNAME }}/buygun:0.3

          EOF
